# Generated by Django 4.0.4 on 2022-07-07 13:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gan_use',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gan_use', models.IntegerField()),
                ('gan_use_datetime', models.DateTimeField()),
            ],
            options={
                'verbose_name': '入室回数',
                'verbose_name_plural': '入室回数',
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.CharField(max_length=100)),
                ('coffee', models.BooleanField(max_length=100)),
                ('job', models.CharField(max_length=100)),
                ('fullname', models.CharField(max_length=100)),
                ('coffee_like', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ユーザー情報',
                'verbose_name_plural': 'ユーザー情報',
            },
        ),
    ]
