# Generated by Django 4.0.4 on 2022-05-29 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basefunction', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name': 'ユーザー情報', 'verbose_name_plural': 'ユーザー情報'},
        ),
    ]
