# Generated by Django 4.0.4 on 2022-05-29 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basefunction', '0002_alter_account_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ganspa_use',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ganspa_use', models.IntegerField()),
            ],
            options={
                'verbose_name': '入室回数',
                'verbose_name_plural': '入室回数',
            },
        ),
    ]
