# Generated by Django 4.0.4 on 2022-05-29 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basefunction', '0004_account2_delete_ganspa_use'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account2',
            options={'verbose_name': 'ユーザー', 'verbose_name_plural': 'ユーザー'},
        ),
        migrations.RemoveField(
            model_name='account2',
            name='user',
        ),
    ]
