# Generated by Django 4.0.4 on 2022-06-04 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basefunction', '0005_alter_account2_options_remove_account2_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gan_use',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gan_use', models.IntegerField()),
                ('gan_use_datetime', models.DateTimeField()),
            ],
            options={
                'verbose_name': '入室回数',
                'verbose_name_plural': '入室回数',
            },
        ),
        migrations.DeleteModel(
            name='Account2',
        ),
    ]
